services:
     - type: web
       name: nxt1me
       env: static
       buildCommand: npm run build
       staticPublishPath: dist
       routes:
         - type: rewrite
           source: /*
           destination: /index.html